[project]
name = "shared"
version = "0.1.0"
description = ""
authors = [
    {name = "Vladyslav Kotliar",email = "kotliarvladyslav@gmail.com"}
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
